apiVersion: v1
kind: Service
metadata:
  name: spring-boot-app-service
  namespace: argocd          
spec:
  type: LoadBalancer
  selector:
    app: spring-boot-app
  ports:
    - name: http
      port: 80
      targetPort: 8080  